#!/usr/bin/env bash
# Ubuntu: system-level setup only. CLI tools, runtimes, and config links (nvim,
# ghostty, zellij, zed, lazygit, .editorconfig, …) come from Home Manager — the
# nix flake. See plans/nix-migration-plan.md.
#
# Runs on a plain Ubuntu host and on Ubuntu under WSL2 (flake host "wsl"). The
# GUI/flatpak block is skipped on WSL, which has no display server of its own;
# the rest (podman socket, pi plugins, gitlab-tui, git hooks) is shared.

# WSL reports Ubuntu's os-release, so detect it explicitly.
is_wsl() { [ -n "${WSL_DISTRO_NAME:-}" ] || grep -qi microsoft /proc/version 2>/dev/null; }

mkdir -p "$HOME/.config"
link_target() {
  local src="$1"
  local dest="$2"
  if [ ! -e "$src" ] && [ ! -L "$src" ]; then
    echo "WARN: source missing, skipping symlink: $src" >&2
    return 1
  fi
  mkdir -p "$(dirname "$dest")"
  rm -rf "$dest"
  ln -s "$src" "$dest"
}

# nvim, ghostty, zellij, zed, herdr config, .editorconfig, lazygit, ideavimrc,
# gradle.properties and ~/.bashrc are managed by Home Manager (home/).
# pi / claude agent configs stay imperative (they carry runtime state).
link_target "$HOME/dotfiles/pi/agent" "$HOME/.agents"
link_target "$HOME/dotfiles/pi" "$HOME/.pi"
link_target "$HOME/dotfiles/.ai" "$HOME/.ai"
link_target "$HOME/dotfiles/claude" "$HOME/.claude"

# herdr config.toml and the systemd unit are managed by Home Manager
# (home/dotfiles.nix, home/herdr.nix). Apply the keybinding to a running server
# immediately (no-op on a fresh install).
herdr server reload-config >/dev/null 2>&1 || true

# ── System packages ───────────────────────────────────────────────────────
# Nix owns the CLI tools and runtimes; apt only carries what Nix cannot provide
# at system level: the OS update, podman's systemd user unit, and — on a
# desktop — flatpak.
sudo apt update
sudo DEBIAN_FRONTEND=noninteractive apt-get -y \
  -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade
sudo apt install -y podman
if ! is_wsl; then
  sudo apt install -y flatpak
fi

# ── GUI apps (desktop only — WSL has no display server of its own) ────────
if ! is_wsl; then
  sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
  flatpak install flathub com.mattjakeman.ExtensionManager com.github.tchx84.Flatseal com.usebruno.Bruno -y
fi

# podman user socket backs $XDG_RUNTIME_DIR/podman/podman.sock (DOCKER_HOST in
# ubuntu/bash_aliases). Guarded: the unit only exists once podman is installed
# and systemd is running.
if command -v systemctl >/dev/null 2>&1 \
   && systemctl --user list-unit-files 2>/dev/null | grep -q '^podman.socket'; then
  systemctl --user enable --now podman.socket
fi

# ~/.bashrc is generated by home/bash.nix and sources bash/* + ubuntu/bashrc,
# so aliases and the Ubuntu PATH/env stay editable without a rebuild.
[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# pi agent binary is installed by the Home Manager activation
# (home/npm-globals.nix). pi plugins are managed by the agent itself — install
# only when pi is present (on a fresh machine, after the first HM switch).
if command -v pi >/dev/null 2>&1; then
  pi install npm:context-mode
  pi install npm:@juicesharp/rpiv-ask-user-question
  pi install npm:pi-subagents
  pi install npm:@dietrichgebert/ponytail
fi

# ── GitLab TUI (gitlab-tui: vim-key GitLab browser) ─────────────────────
# Builds from source (go.mod declares module 'gitlab-tui', so `go install
# @latest` fails) and writes ~/.config/gitlab-tui/config.json for $GITLAB_HOST.
# ~/.local/bin is on PATH via ubuntu/bashrc.
if command -v gitlab-tui >/dev/null 2>&1; then
  echo "gitlab-tui already installed: $(command -v gitlab-tui)"
elif command -v go >/dev/null 2>&1 && command -v make >/dev/null 2>&1; then
  git clone -q --depth 1 https://github.com/nospor/gitlab-tui /tmp/gitlab-tui-build
  if make -C /tmp/gitlab-tui-build install PREFIX="$HOME/.local"; then
    echo "gitlab-tui installed to $HOME/.local/bin"
  else
    echo "WARN: gitlab-tui build failed — re-run or install manually (github.com/nospor/gitlab-tui)" >&2
  fi
  rm -rf /tmp/gitlab-tui-build
else
  echo "WARN: go/make missing — skipping gitlab-tui build (go+gcc+gnumake come from home/packages.nix)" >&2
fi

# config: GitLab server ($GITLAB_HOST, e.g. https://<gitlab-host>); token from $GITLAB_TOKEN, else placeholder
mkdir -p "$HOME/.config/gitlab-tui"
python3 - "${GITLAB_TOKEN:-__PASTE_GITLAB_TOKEN_HERE__}" "${GITLAB_HOST:-https://<gitlab-host>}" <<'PYEOF'
import json, os, sys
cfg = {"servers": [{"name": sys.argv[2], "url": sys.argv[2], "token": sys.argv[1], "default": True}], "theme": "catppuccin"}
os.makedirs(os.path.expanduser("~/.config/gitlab-tui"), exist_ok=True)
with open(os.path.expanduser("~/.config/gitlab-tui/config.json"), "w") as f:
    json.dump(cfg, f, indent=2)
PYEOF
if [ -n "${GITLAB_TOKEN:-}" ]; then
  echo "gitlab-tui configured for $GITLAB_HOST (token from GITLAB_TOKEN)"
else
  echo "NOTE: GITLAB_TOKEN not set — edit ~/.config/gitlab-tui/config.json and paste your token"
fi

[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# Git identity is managed by Home Manager (home/git.nix). Do not set it here —
# a ~/.gitconfig would shadow the HM-managed ~/.config/git/config.
# repo-local identifier pre-commit hook (see AGENTS.md "Identifier hygiene")
git -C "$HOME/dotfiles" config core.hooksPath .githooks
