for alias_file in "$HOME/dotfiles/bash/"*; do
  [[ -f "$alias_file" ]] && source "$alias_file"
done

[[ -f "$HOME/dotfiles/macos/bash_alias" ]] && source "$HOME/dotfiles/macos/bash_alias"

alias crc="cat ~/.zshrc"
alias erc="nvim ~/.zshrc"
alias src="source ~/.zshrc"

PROMPT='%n@%m %1~%# '


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
