for alias_file in "$HOME/dotfiles/bash/"*; do
  [ -f "$alias_file" ] && . "$alias_file"
done

[ -f "$HOME/dotfiles/nobara/bash_aliases" ] && . "$HOME/dotfiles/nobara/bash_aliases"

PS1='\u@\h \W\$ '

export PATH="$HOME/.local/bin:$PATH"
eval "$(mise activate bash)"
export PATH=$HOME/.local/bin:$PATH
