alias i="sudo dnf install"
alias r="sudo dnf remove"
alias is="dnf search"
alias up="nobara-sync cli && yes | flatpak update"
alias il="dnf list"

export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"
export DOCKER_SOCK="$XDG_RUNTIME_DIR/podman/podman.sock"
