#!/usr/bin/env bash
mkdir -p "$HOME/.config" "$HOME/.config/ghostty"
link_target() {
  local src="$1"
  local dest="$2"
  if [ ! -e "$src" ] && [ ! -L "$src" ]; then
    echo "WARN: source missing, skipping symlink: $src" >&2
    return 1
  fi
  mkdir -p "$(dirname "$dest")"
  rm -rf "$dest"
  ln -s "$src" "$dest"
}
sudo_link_target() {
  local src="$1"
  local dest="$2"
  sudo rm -rf "$dest"
  sudo ln -s "$src" "$dest"
}

sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y

# nvim, ghostty, zellij, zed, herdr config, .editorconfig, lazygit, ideavimrc,
# gradle.properties and ~/.bashrc are managed by Home Manager (home/).
link_target "$HOME/dotfiles/pi/agent" "$HOME/.agents"
link_target "$HOME/dotfiles/pi" "$HOME/.pi"
link_target "$HOME/dotfiles/.ai" "$HOME/.ai"
link_target "$HOME/dotfiles/claude" "$HOME/.claude"
# herdr config.toml and the systemd unit are managed by Home Manager
# (home/dotfiles.nix, home/herdr.nix).
# Apply the keybinding to a running herdr server immediately (no-op on fresh installs).
herdr server reload-config >/dev/null 2>&1 || true

# herdr headless server + boot restore is managed by Home Manager
# (systemd.user.services.herdr-server in home/herdr.nix) — nothing to do here.

sudo_link_target "$HOME/dotfiles/nobara/dnf.conf" "/etc/dnf/dnf.conf"

# ~/.bashrc is generated by home/bash.nix and sources nobara/bashrc.
[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# CLI tools, runtimes, and git identity are managed by Home Manager (home/).
# No copr/dnf/pip/mise/npm/cargo installs here. Platform packages Nix does not
# manage stay: nobara-sync, the Zed app, flatpak apps, media codecs.
nobara-sync cli && yes | flatpak update
sudo dnf install mpv-libs -y --skip-unavailable

# Zed app (its config is symlinked by Home Manager).
curl -f https://zed.dev/install.sh | sh

sudo dnf install -y flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.mattjakeman.ExtensionManager com.github.tchx84.Flatseal -y

# pi agent binary is installed by the Home Manager activation
# (home/npm-globals.nix). pi plugins are managed by the agent itself — install
# only when pi is present (on a fresh machine, after the first HM switch).
if command -v pi >/dev/null 2>&1; then
  pi install npm:context-mode
  pi install npm:@juicesharp/rpiv-ask-user-question
  pi install npm:pi-subagents
  pi install npm:@dietrichgebert/ponytail
fi

# ── GitLab TUI (gitlab-tui: vim-key GitLab browser) ─────────────────────
# Builds from source (go.mod declares module 'gitlab-tui', so `go install
# @latest` fails) and writes ~/.config/gitlab-tui/config.json for $GITLAB_HOST.
# ~/.local/bin is on PATH via nobara/bashrc.
if command -v gitlab-tui >/dev/null 2>&1; then
  echo "gitlab-tui already installed: $(command -v gitlab-tui)"
elif command -v go >/dev/null 2>&1 && command -v make >/dev/null 2>&1; then
  git clone -q --depth 1 https://github.com/nospor/gitlab-tui /tmp/gitlab-tui-build
  if make -C /tmp/gitlab-tui-build install PREFIX="$HOME/.local"; then
    echo "gitlab-tui installed to $HOME/.local/bin"
  else
    echo "WARN: gitlab-tui build failed — re-run or install manually (github.com/nospor/gitlab-tui)" >&2
  fi
  rm -rf /tmp/gitlab-tui-build
else
  echo "WARN: go/make missing — skipping gitlab-tui build (go+gcc+gnumake come from home/packages.nix)" >&2
fi

# config: scripts/gitlab-tui-config.sh writes ~/.config/gitlab-tui/config.json
# from the untracked GITLAB_HOST/GITLAB_TOKEN in bash/secret_aliases. It never
# writes a placeholder — a placeholder host is what broke gitlab-tui
# ("lookup <gitlab-host>: no such host"). Unlike `source ~/.bashrc`, it reads
# the secrets even when install.sh runs non-interactively.
"$HOME/dotfiles/scripts/gitlab-tui-config.sh"

# podman socket backs $XDG_RUNTIME_DIR/podman/podman.sock (DOCKER_HOST in
# nobara/bash_aliases).
systemctl --user enable --now podman.socket

[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# Git identity is managed by Home Manager (home/git.nix). Do not set it here —
# a ~/.gitconfig would shadow the HM-managed ~/.config/git/config.
# repo-local identifier pre-commit hook (see AGENTS.md "Identifier hygiene")
git -C "$HOME/dotfiles" config core.hooksPath .githooks
