#!/usr/bin/env bash
mkdir -p "$HOME/.config" "$HOME/.config/ghostty"
link_target() {
  local src="$1"
  local dest="$2"
  if [ ! -e "$src" ] && [ ! -L "$src" ]; then
    echo "WARN: source missing, skipping symlink: $src" >&2
    return 1
  fi
  mkdir -p "$(dirname "$dest")"
  rm -rf "$dest"
  ln -s "$src" "$dest"
}

# Arch has no RPM Fusion equivalent — everything Nix does not manage comes from
# the official repos (the package list below), so nothing to add to pacman.conf.
sudo pacman -Syu --noconfirm

# nvim, ghostty, and zed configs are managed by Home Manager
# (home/dotfiles.nix); ~/.bashrc is generated by home/bash.nix.
link_target "$HOME/dotfiles/pi/agent" "$HOME/.agents"
link_target "$HOME/dotfiles/pi" "$HOME/.pi"
link_target "$HOME/dotfiles/.ai" "$HOME/.ai"
link_target "$HOME/dotfiles/claude" "$HOME/.claude"
# orca user config dir (~/.orca holds keybindings.json overrides).
# ~/.config/orca is Electron app data holding a private key + tokens: never linked.
link_target "$HOME/dotfiles/orca" "$HOME/.orca"
# herdr config.toml and the systemd unit are managed by Home Manager
# (home/dotfiles.nix, home/herdr.nix).
# Apply the keybinding to a running herdr server immediately (no-op on fresh installs).
herdr server reload-config >/dev/null 2>&1 || true

# herdr headless server + boot restore is managed by Home Manager
# (systemd.user.services.herdr-server in home/herdr.nix) — nothing to do here.

# Platform packages Nix does not manage: zram generator, media codecs (mpv
# carries libmpv), flatpak, and podman (daemon + user socket).
sudo pacman -S --needed --noconfirm zram-generator mpv flatpak podman

## zram swap scaling + zstd (see arch/zram-generator.conf for the reasoning).
## Copied, not symlinked: zram-generator runs early in boot, before a $HOME
## symlink target is guaranteed to be readable.
sudo cp "$HOME/dotfiles/arch/zram-generator.conf" /etc/systemd/zram-generator.conf
sudo systemctl daemon-reload
sudo systemctl restart systemd-zram-setup@zram0.service

# Zed app (its config is symlinked by Home Manager). Upstream's installer, not
# the repo package: it tracks the release channel.
curl -f https://zed.dev/install.sh | sh

# lazygit, ideavimrc, and gradle.properties are managed by Home Manager
# (home/dotfiles.nix). ~/.bashrc is generated by home/bash.nix and sources
# $HOME/dotfiles/arch/bashrc, so aliases stay editable without a rebuild.
[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# TODO(pi-npm-migration): delete this block once every host has run it — pi used
# to be an npm global in ~/.local and is now the flake's package
# (home/packages.nix). The leftover npm copy shadows the flake one on PATH,
# because arch/bashrc puts ~/.local/bin ahead of ~/.nix-profile/bin.
legacy_pi="$HOME/.local/lib/node_modules/@earendil-works/pi-coding-agent"
if [ -d "$legacy_pi" ]; then
  echo "Migrating pi off npm (it is the flake's package now)..."
  command -v npm >/dev/null 2>&1 && npm_config_prefix="$HOME/.local" \
    npm uninstall -g @earendil-works/pi-coding-agent >/dev/null 2>&1
  # Also remove directly: covers a shell with no npm on PATH, and npm keeps no
  # state here (no .package-lock.json in ~/.local/lib/node_modules).
  rm -rf "$HOME/.local/bin/pi" "$legacy_pi"
  rmdir "$HOME/.local/lib/node_modules/@earendil-works" 2>/dev/null || true
fi

# The pi agent binary comes from the flake (home/packages.nix -> the upstream pi
# flake input). pi plugins are managed by the agent itself — install only when
# pi is present (on a fresh machine, after the first HM switch).
if command -v pi >/dev/null 2>&1; then
  pi install npm:context-mode
  pi install npm:@juicesharp/rpiv-ask-user-question
  pi install npm:pi-subagents
  pi install npm:@dietrichgebert/ponytail
  pi install npm:pi-btw
fi


# ── GitLab TUI (gitlab-tui: vim-key GitLab browser) ─────────────────────
# Builds from source (go.mod declares module 'gitlab-tui', so `go install
# @latest` fails) and writes ~/.config/gitlab-tui/config.json for $GITLAB_HOST.
# ~/.local/bin is on PATH via arch/bashrc.
if command -v gitlab-tui >/dev/null 2>&1; then
  echo "gitlab-tui already installed: $(command -v gitlab-tui)"
elif command -v go >/dev/null 2>&1 && command -v make >/dev/null 2>&1; then
  git clone -q --depth 1 https://github.com/nospor/gitlab-tui /tmp/gitlab-tui-build
  if make -C /tmp/gitlab-tui-build install PREFIX="$HOME/.local"; then
    echo "gitlab-tui installed to $HOME/.local/bin"
  else
    echo "WARN: gitlab-tui build failed — re-run or install manually (github.com/nospor/gitlab-tui)" >&2
  fi
  rm -rf /tmp/gitlab-tui-build
else
  echo "WARN: go/make missing — skipping gitlab-tui build (go+gcc+gnumake come from home/packages.nix)" >&2
fi

# config: scripts/gitlab-tui-config.sh writes ~/.config/gitlab-tui/config.json
# from the untracked GITLAB_HOST/GITLAB_TOKEN in bash/secret_aliases. It never
# writes a placeholder — a placeholder host is what broke gitlab-tui
# ("lookup <gitlab-host>: no such host"). Unlike `source ~/.bashrc`, it reads
# the secrets even when install.sh runs non-interactively.
"$HOME/dotfiles/scripts/gitlab-tui-config.sh"

sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.mattjakeman.ExtensionManager com.github.tchx84.Flatseal com.usebruno.Bruno com.anydesk.Anydesk com.discordapp.Discord com.viber.Viber org.jellyfin.JellyfinDesktop org.onlyoffice.desktopeditors -y

# podman user socket backs $XDG_RUNTIME_DIR/podman/podman.sock (DOCKER_HOST in
# arch/bash_aliases). Guarded: the unit only exists once systemd is running
# (a container has no user session).
if command -v systemctl >/dev/null 2>&1 \
   && systemctl --user list-unit-files 2>/dev/null | grep -q '^podman.socket'; then
  systemctl --user enable --now podman.socket
fi

# Git identity is managed by Home Manager (home/git.nix). Do not set it here —
# a ~/.gitconfig would shadow the HM-managed ~/.config/git/config.
# repo-local identifier pre-commit hook (see AGENTS.md "Identifier hygiene")
git -C "$HOME/dotfiles" config core.hooksPath .githooks
