alias i="sudo dnf install"
alias r="sudo dnf remove"
alias up="sudo dnf up"
alias is="dnf search"
alias il="dnf list"

export DOCKER_HOST="unix://$XDG_RUNTIME_DIR/podman/podman.sock"
export DOCKER_SOCK="$XDG_RUNTIME_DIR/podman/podman.sock"
