for alias_file in "$HOME/dotfiles/bash/"*; do
  [ -f "$alias_file" ] && . "$alias_file"
done

[ -f "$HOME/dotfiles/fedora/bash_aliases" ] && . "$HOME/dotfiles/fedora/bash_aliases"

PS1='\u@\h \W\$ '
eval "$(mise activate bash)"
export PATH="$HOME/.cargo/bin:$PATH"

# Pi
export PATH="$HOME/.local/share/mise/installs/node/24.17.0/bin:$PATH"
