mkdir -p "$HOME/.config" "$HOME/.config/ghostty"
link_target() {
  local src="$1"
  local dest="$2"
  if [ ! -e "$src" ] && [ ! -L "$src" ]; then
    echo "WARN: source missing, skipping symlink: $src" >&2
    return 1
  fi
  mkdir -p "$(dirname "$dest")"
  rm -rf "$dest"
  ln -s "$src" "$dest"
}
sudo_link_target() {
  local src="$1"
  local dest="$2"
  sudo rm -rf "$dest"
  sudo ln -s "$src" "$dest"
}

sudo dnf install https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm -y

# nvim, ghostty, zed, and zellij configs are managed by Home Manager
# (home/dotfiles.nix); ~/.bashrc is generated by home/bash.nix.
link_target "$HOME/dotfiles/pi/agent" "$HOME/.agents"
link_target "$HOME/dotfiles/pi" "$HOME/.pi"
link_target "$HOME/dotfiles/.ai" "$HOME/.ai"
link_target "$HOME/dotfiles/claude" "$HOME/.claude"
# herdr config.toml is managed by Home Manager (home/dotfiles.nix); the
# systemd unit below stays imperative.
# Apply the keybinding to a running herdr server immediately (no-op on fresh installs).
herdr server reload-config >/dev/null 2>&1 || true

# herdr headless server + boot restore (nvim/pi/terminal per workspace)
mkdir -p "$HOME/.config/systemd/user"
cp "$HOME/dotfiles/herdr/systemd/herdr-server.service" "$HOME/.config/systemd/user/herdr-server.service"
systemctl --user daemon-reload
systemctl --user enable herdr-server.service

sudo_link_target "$HOME/dotfiles/fedora/dnf.conf" "/etc/dnf/dnf.conf"

## zram swap scaling + zstd (see fedora/zram-generator.conf for the reasoning).
## Copied, not symlinked: zram-generator runs early in boot, before a $HOME
## symlink target is guaranteed to be readable.
sudo cp "$HOME/dotfiles/fedora/zram-generator.conf" /etc/systemd/zram-generator.conf
sudo systemctl daemon-reload
sudo systemctl restart systemd-zram-setup@zram0.service

# lazygit, ideavimrc, and gradle.properties are managed by Home Manager
# (home/dotfiles.nix). ~/.bashrc is generated by home/bash.nix and sources
# $HOME/dotfiles/fedora/bashrc, so aliases stay editable without a rebuild.
[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# CLI tools, runtimes, and git identity are managed by Home Manager (home/).
# No copr/dnf/pip/mise/npm installs here. Only platform packages Nix does not
# manage stay: RPM Fusion (above) and media codecs.
sudo dnf update -y
sudo dnf install mpv-libs -y --skip-unavailable

# pi agent binary is installed by the Home Manager activation
# (home/npm-globals.nix). pi plugins are managed by the agent itself — install
# only when pi is present (on a fresh machine, after the first HM switch).
if command -v pi >/dev/null 2>&1; then
  pi install npm:context-mode
  pi install npm:@juicesharp/rpiv-ask-user-question
  pi install npm:pi-subagents
  pi install npm:@dietrichgebert/ponytail
fi


# ── GitLab TUI (gitlab-tui: vim-key GitLab browser) ─────────────────────
# Builds from source (go.mod declares module 'gitlab-tui', so `go install
# @latest` fails) and writes ~/.config/gitlab-tui/config.json for $GITLAB_HOST.
# ~/.local/bin is on PATH via fedora/bashrc.
if command -v gitlab-tui >/dev/null 2>&1; then
  echo "gitlab-tui already installed: $(command -v gitlab-tui)"
elif command -v go >/dev/null 2>&1 && command -v make >/dev/null 2>&1; then
  git clone -q --depth 1 https://github.com/nospor/gitlab-tui /tmp/gitlab-tui-build
  if make -C /tmp/gitlab-tui-build install PREFIX="$HOME/.local"; then
    echo "gitlab-tui installed to $HOME/.local/bin"
  else
    echo "WARN: gitlab-tui build failed — re-run or install manually (github.com/nospor/gitlab-tui)" >&2
  fi
  rm -rf /tmp/gitlab-tui-build
else
  echo "WARN: go/make missing — skipping gitlab-tui build (go+gcc+gnumake come from home/packages.nix)" >&2
fi

# config: GitLab server ($GITLAB_HOST, e.g. https://<gitlab-host>); token from $GITLAB_TOKEN, else placeholder
mkdir -p "$HOME/.config/gitlab-tui"
python3 - "${GITLAB_TOKEN:-__PASTE_GITLAB_TOKEN_HERE__}" "${GITLAB_HOST:-https://<gitlab-host>}" <<'PYEOF'
import json, os, sys
cfg = {"servers": [{"name": sys.argv[2], "url": sys.argv[2], "token": sys.argv[1], "default": True}], "theme": "catppuccin"}
os.makedirs(os.path.expanduser("~/.config/gitlab-tui"), exist_ok=True)
with open(os.path.expanduser("~/.config/gitlab-tui/config.json"), "w") as f:
    json.dump(cfg, f, indent=2)
PYEOF
if [ -n "${GITLAB_TOKEN:-}" ]; then
  echo "gitlab-tui configured for $GITLAB_HOST (token from GITLAB_TOKEN)"
else
  echo "NOTE: GITLAB_TOKEN not set — edit ~/.config/gitlab-tui/config.json and paste your token"
fi

sudo dnf install -y flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub com.mattjakeman.ExtensionManager com.github.tchx84.Flatseal com.usebruno.Bruno -y

systemctl --user enable --now podman.socket

source "$HOME/.bashrc"

# Git identity is managed by Home Manager (home/git.nix). Do not set it here —
# a ~/.gitconfig would shadow the HM-managed ~/.config/git/config.
# repo-local identifier pre-commit hook (see AGENTS.md "Identifier hygiene")
git -C "$HOME/dotfiles" config core.hooksPath .githooks
