vim.g.mapleader = " "

local keymap = vim.keymap

-- ── File & project navigation ───────────────────────
keymap.set("n", "<leader>ee", function()
	Snacks.explorer()
end, { desc = "Toggle file explorer" })
keymap.set("n", "<M-1>", function()
	Snacks.explorer()
end, { desc = "Toggle file explorer (Alt+1)" })
keymap.set("n", "<leader>ef", function()
	Snacks.explorer.reveal()
end, { desc = "Reveal current file in explorer" })
keymap.set("n", "<C-n>", function()
	Snacks.picker.files()
end, { desc = "Find file (Ctrl+N)" })
keymap.set("n", "<leader>ff", function()
	Snacks.picker.files()
end, { desc = "Find file by name" })
keymap.set("n", "<C-e>", function()
	Snacks.picker.recent()
end, { desc = "Recent files (Ctrl+E)" })
keymap.set("n", "<leader>fr", function()
	Snacks.picker.recent()
end, { desc = "Recent files" })
keymap.set("n", "<leader>fs", function()
	Snacks.picker.grep()
end, { desc = "Search text in project (grep)" })
keymap.set("n", "<leader>fc", function()
	Snacks.picker.grep_word()
end, { desc = "Search word under cursor" })
keymap.set("n", "<leader>ft", function()
	Snacks.picker.todo_comments()
end, { desc = "Find TODOs" })

-- ── Git ─────────────────────────────────────────────
keymap.set("n", "<leader>lg", function()
	Snacks.lazygit()
end, { desc = "LazyGit (full TUI)" })
keymap.set("n", "<leader>lc", function()
	Snacks.lazygit()
end, { desc = "Commit (lazygit)" })
keymap.set("n", "<leader>lp", function()
	Snacks.lazygit()
end, { desc = "Push (lazygit)" })
keymap.set("n", "<leader>lu", function()
	Snacks.lazygit()
end, { desc = "Pull (lazygit)" })

-- ── LSP / code intelligence ─────────────────────────
-- Global LSP mappings (using Snacks picker where appropriate)
keymap.set("n", "gd", function()
	Snacks.picker.lsp_definitions()
end, { desc = "Go to definition" })
keymap.set("n", "gi", function()
	Snacks.picker.lsp_implementations()
end, { desc = "Go to implementation" })
keymap.set("n", "gt", function()
	Snacks.picker.lsp_type_definitions()
end, { desc = "Go to type definition" })
keymap.set("n", "gR", function()
	Snacks.picker.lsp_references()
end, { desc = "Find references" })
keymap.set("n", "K", vim.lsp.buf.hover, { desc = "Hover / documentation" })
keymap.set({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, { desc = "Code actions / intentions" })
keymap.set("n", "<leader>rn", vim.lsp.buf.rename, { desc = "Rename" })
keymap.set("n", "[d", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })
keymap.set("n", "]d", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
keymap.set("n", "<F2>", vim.diagnostic.goto_next, { desc = "Next diagnostic" })
keymap.set("n", "<S-F2>", vim.diagnostic.goto_prev, { desc = "Previous diagnostic" })
keymap.set("n", "<leader>xx", function()
	Snacks.picker.diagnostics()
end, { desc = "Toggle diagnostics list" })
keymap.set("n", "<leader>xd", function()
	Snacks.picker.diagnostics_buffer()
end, { desc = "Buffer diagnostics" })

-- ── Terminal ────────────────────────────────────────
keymap.set({ "n", "t" }, "<leader>ot", function()
	Snacks.terminal()
end, { desc = "Toggle terminal" })
keymap.set("n", "<leader>oT", function()
	Snacks.terminal(nil, {
		win = { position = "float", border = "rounded", width = 0.9, height = 0.9 },
	})
end, { desc = "Floating terminal" })

-- ── Build & run ─────────────────────────────────────
keymap.set("n", "<leader>rb", function()
	print("Use zellij bash pane for run")
end, { desc = "Run (Zellij)" })
keymap.set("n", "<leader>rd", function()
	require("dap").continue()
end, { desc = "Start / continue debug" })

-- ── Debug (DAP) ─────────────────────────────────────
keymap.set("n", "<F5>", function()
	require("dap").continue()
end, { desc = "Continue" })
keymap.set("n", "<F10>", function()
	require("dap").step_over()
end, { desc = "Step over" })
keymap.set("n", "<F11>", function()
	require("dap").step_into()
end, { desc = "Step into" })
keymap.set("n", "<S-F11>", function()
	require("dap").step_out()
end, { desc = "Step out" })
keymap.set("n", "<leader>dt", function()
	require("dap").toggle_breakpoint()
end, { desc = "Toggle breakpoint" })
keymap.set("n", "<leader>du", function()
	require("dapui").toggle()
end, { desc = "Toggle DAP UI" })
keymap.set("n", "<leader>de", function()
	require("dapui").eval()
end, { desc = "Evaluate expression" })
keymap.set("n", "<leader>dr", function()
	require("dap").run_to_cursor()
end, { desc = "Run to cursor" })
keymap.set("n", "<leader>dR", function()
	require("dap").restart()
end, { desc = "Restart debug session" })
keymap.set("n", "<leader>dq", function()
	require("dap").terminate()
end, { desc = "Terminate debug session" })

-- ── Tools ───────────────────────────────────────────
keymap.set("n", "<leader>ai", "<cmd>PiToggle<CR>", { desc = "Pi AI Assistant" })
keymap.set("n", "<leader>db", function()
	print("Use DataGrip for database")
end, { desc = "Database (DataGrip)" })
keymap.set("n", "<leader>mv", function()
	print("Use zellij bash pane for maven")
end, { desc = "Maven (Zellij)" })

-- ── General editing ─────────────────────────────────
keymap.set("n", "<leader>nh", ":nohl<CR>", { desc = "Clear search highlights" })
keymap.set("n", "<leader>si", "<cmd>source $MYVIMRC<CR>", { desc = "Reload Neovim config" })
keymap.set("n", "<leader>+", "<C-a>", { desc = "Increment number" })
keymap.set("n", "<leader>-", "<C-x>", { desc = "Decrement number" })

-- ── Buffer tabs (akinsho/bufferline.nvim) ───────────
keymap.set("n", "<leader>tt", "<cmd>enew<CR>", { desc = "New empty buffer" })
keymap.set("n", "<leader>tw", "<cmd>bdelete!<CR>", { desc = "Close current buffer" })
keymap.set("n", "<leader>to", function()
  local curbuf = vim.api.nvim_get_current_buf()
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    if buf ~= curbuf and vim.bo[buf].buflisted then
      pcall(vim.api.nvim_buf_delete, buf, { force = true })
    end
  end
end, { desc = "Close other buffers" })
keymap.set("n", "<M-l>", "<cmd>BufferLineCycleNext<CR>", { desc = "Next buffer" })
keymap.set("n", "<M-h>", "<cmd>BufferLineCyclePrev<CR>", { desc = "Previous buffer" })
keymap.set("n", "<leader>tl", "<cmd>BufferLineMoveNext<CR>", { desc = "Move buffer right" })
keymap.set("n", "<leader>th", "<cmd>BufferLineMovePrev<CR>", { desc = "Move buffer left" })
keymap.set("n", "<leader>t1", "<cmd>BufferLineGoToBuffer 1<CR>", { desc = "Go to buffer 1" })
keymap.set("n", "<leader>t2", "<cmd>BufferLineGoToBuffer 2<CR>", { desc = "Go to buffer 2" })
keymap.set("n", "<leader>t3", "<cmd>BufferLineGoToBuffer 3<CR>", { desc = "Go to buffer 3" })
keymap.set("n", "<leader>t4", "<cmd>BufferLineGoToBuffer 4<CR>", { desc = "Go to buffer 4" })
keymap.set("n", "<leader>t5", "<cmd>BufferLineGoToBuffer 5<CR>", { desc = "Go to buffer 5" })
keymap.set("n", "<leader>t6", "<cmd>BufferLineGoToBuffer 6<CR>", { desc = "Go to buffer 6" })
keymap.set("n", "<leader>t7", "<cmd>BufferLineGoToBuffer 7<CR>", { desc = "Go to buffer 7" })
keymap.set("n", "<leader>t8", "<cmd>BufferLineGoToBuffer 8<CR>", { desc = "Go to buffer 8" })
keymap.set("n", "<leader>t9", "<cmd>BufferLineGoToBuffer 9<CR>", { desc = "Go to buffer 9" })
